image: chef/chefdk:current

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  KITCHEN_LOCAL_YAML: .kitchen.dokken.yml

services:
  - docker:dind

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - apt-get update && apt-get install rsync -y

test:ChefDK:
  cache:
    paths:
      - .bundle
      - vendor/bundle
  script:
    - chef exec delivery local lint
    - chef exec delivery local syntax
    - chef exec delivery local unit
    - chef exec kitchen test default
    - chef exec kitchen test resource
  tags:
    - chefdk
